services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adachi
      - MONGO_INITDB_ROOT_PASSWORD=adachi
volumes:
  mongo: {}