_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.2
            "8":
                - 3
                - 5
            "12": 0.19.2
            "13": windows-amd64
C:
    value: 1
gamma:
    value: 0.1
kernel:
    value: rbf
