_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.2
            "8":
                - 3
                - 5
            "12": 0.19.2
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 5
learning_rate:
    value: 0.01
